name: capstone
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - expat=2.7.3
  - faiss-cpu=1.9.0
  - intel-openmp=2023.1.0
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libzlib=1.3.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2021.8.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arxiv==2.2.0
      - attrs==25.4.0
      - blinker==1.9.0
      - blis==0.7.11
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - confection==0.1.5
      - cryptography==46.0.3
      - cymem==2.0.13
      - dataclasses-json==0.6.7
      - en-core-web-sm==3.7.1
      - faiss==1.9.0
      - feedparser==6.0.12
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - habanero==1.2.6
      - httpcore==1.0.9
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - langchain==0.3.0
      - langchain-community==0.3.0
      - langchain-core==0.3.63
      - langchain-text-splitters==0.3.8
      - langcodes==3.5.0
      - langsmith==0.1.147
      - language-data==1.3.0
      - llvmlite==0.45.1
      - lxml==6.0.2
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - murmurhash==1.0.15
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numba==0.62.1
      - ollama==0.3.1
      - openai-whisper==20250625
      - orjson==3.11.4
      - packaging==24.2
      - pandas==2.2.2
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - pillow==10.4.0
      - pluggy==1.6.0
      - preshed==3.0.12
      - propcache==0.4.1
      - protobuf==5.29.5
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pygments==2.19.2
      - pymupdf==1.24.10
      - pymupdfb==1.24.10
      - pypdfium2==5.0.0
      - pytest==8.3.2
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.29.0
      - safetensors==0.6.2
      - scikit-learn==1.5.1
      - scipy==1.16.3
      - semanticscholar==0.9.0
      - sentence-transformers==3.0.1
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.7.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - srsly==2.5.2
      - streamlit==1.38.0
      - sympy==1.14.0
      - tenacity==8.5.0
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - watchdog==4.0.2
      - weasel==0.4.3
      - wrapt==2.0.1
      - yarl==1.22.0
prefix: C:\Users\redua\Miniconda3\envs\capstone
